[theme.variables]
black = "#181825"
bg = "#1e1e2e"
gray = "#313244"
black4 = "#4e5166"
surface = "#6c7086"
surface1 = "#a6adc8"
fg = "#cdd6f4"
cyan = "#89dceb"
magenta = "#cba6f7"
pink = "#f5c2e7"
redActive = '#eba0ac'
red = "#f38ba8"
greenActive = "#94e2d5"
green = "#a6e3a1"
yellowActive = "#f5e0dc"
yellow = "#f9e2af"
blueActive = "#b4befe"
blue = "#89b4fa"
orangeActive = "#f2cdcd"
orange = "#fab387"
