gui:
  scrollHeight: 2
  language: "auto"
  border: "rounded"
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - blue
    selectedLineBgColor:
      - black
      - underline
    optionsTextColor:
      - green
