[shell.files]
"shell/pwsh.ps1" = "~/.config/powershell/Microsoft.PowerShell_profile.ps1"
"shell/.bashrc" = "~/.bashrc"
"shell/starship.toml" = "~/.config/starship.toml"

[twm.files]
"twm/hypr" = "~/.config/hypr"
"twm/hypr/waybar" = "~/.config/waybar"

[tui.files]
"tui/euporie" = "~/.config/euporie"
"tui/yazi" = "~/.config/yazi"
