[shell.files]
"shell/pwsh.ps1" = "~/powershell/Microsoft.PowerShell_profile.ps1"
"shell/.zshrc" = "~/.zshrc"
"shell/starship.toml" = "~/.config/starship.toml"

[twm.files]
"twm/hyprland/hyprland.conf" = "~/.config/hyprland/hyprland.conf"

[tui.files]
"tui/euporie" = "~/.config/euporie"
"tui/ranger" = "~/.config/ranger"

