[shell.files]
"shell/pwsh.ps1" = "~/OneDrive/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"shell/starship.toml" = "~/.config/starship.toml"

[twm.files]
"twm/glazewm/config.yaml" = "~/.glzr/glazewm/config.yaml"
