[vscode.files]
"editor/vscode" = "~/AppData/Roaming/Code/User"

[nvim.files]
"editor/nvim" = "~/AppData/Local/nvim"

[shell.files]
"shell/.bashrc" = "~/.bashrc"
"shell/pswh.ps1" = "~/Documents/Powershell/pwsh.ps1"

[tui]
depends = ["theme"]

[tui.files]
"tui/lazygit/config.yml" = "~/.config/lazygit/config.yml"
"tui/lazydocker/config.yml" = "~/.config/lazydocker/config.yml"
"tui/k9s/config.yaml" = "~/.config/k9s/config.yaml"
"tui/k9s/theme.yaml" = "~/.config/k9s/skins/theme.yaml"
