general:
  startup_commands: ['shell-exec zebar']
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']
  config_reload_commands: []
  focus_follows_cursor: true
  toggle_workspace_on_refocus: false

  cursor_jump:
    enabled: true
    trigger: 'monitor_focus'

gaps:
  inner_gap: '20px'

  outer_gap:
    top: '60px'
    right: '20px'
    bottom: '20px'
    left: '20px'

window_effects:
  focused_window:
    border:
      enabled: true
      color: '{{ blue }}'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: 'rounded'

  other_windows:
    border:
      enabled: true
      color: '{{ mauve }}'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: 'rounded'

window_behavior:
  initial_state: 'tiling'
  state_defaults:
    floating:
      centered: true
      shown_on_top: false

    fullscreen:
      maximized: false
      shown_on_top: false

workspaces:
  - name: '1'
  - name: '2'
  - name: '3'
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'

window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'zebar' }
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper*' }

keybindings:
  - commands: ['focus --direction left']
    bindings: ['{{ mod }}+{{ lower focus_left }}']
  - commands: ['focus --direction right']
    bindings: ['{{ mod }}+{{ lower focus_right }}']
  - commands: ['focus --direction up']
    bindings: ['{{ mod }}+{{ lower focus_up }}']
  - commands: ['focus --direction down']
    bindings: ['{{ mod }}+{{ lower focus_down }}']
  - commands: ['move --direction left']
    bindings: ['{{ mod }}+{{ lower move_left }}']
  - commands: ['move --direction right']
    bindings: ['{{ mod }}+{{ lower move_right }}']
  - commands: ['move --direction up']
    bindings: ['{{ mod }}+{{ lower move_left }}']
  - commands: ['move --direction down']
    bindings: ['{{ mod }}+{{ lower move_down }}']
  - commands: ['resize --width -2%']
    bindings: ['{{ mod }}+{{ lower decrease_width }}']
  - commands: ['resize --width +2%']
    bindings: ['{{ mod }}+{{ lower increase_width }}']
  - commands: ['resize --height +2%']
    bindings: ['{{ mod }}+{{ lower increase_height }}']
  - commands: ['resize --height -2%']
    bindings: ['{{ mod }}+{{ lower decrease_height }}']
  - commands: ['toggle-tiling-direction']
    bindings: ['{{ mod }}+{{ lower toggle_split }}']
  - commands: ['toggle-fullscreen']
    bindings: ['{{ mod }}+{{ lower fullscreen }}']
  - commands: ['toggle-minimized']
    bindings: ['{{ mod }}+{{ lower minimize }}']
  - commands: ['close']
    bindings: ['{{ mod }}+{{ lower quit }}']
  - commands: ['wm-exit']
    bindings: ['{{ mod }}+{{ lower exit }}']
  - commands: ['wm-reload-config']
    bindings: ['{{ mod }}+{{ lower restart }}']
  - commands: ['wm-redraw']
    bindings: ['{{ mod }}+shift+w']
  - commands: ['shell-exec {{ terminal }}']
    bindings: ['{{ mod }}+{{ open_terminal }}']
  - commands: ['focus --next-workspace']
    bindings: ['{{ mod }}+{{ next_workspace }}']
  - commands: ['focus --prev-workspace']
    bindings: ['{{ mod }}+{{ prev_workspace }}']
  - commands: ['focus --recent-workspace']
    bindings: ['{{ mod }}+{{ recent_workspace }}']
  - commands: ['focus --workspace 1']
    bindings: ['{{ mod }}+{{ focus_workspace_1 }}']
  - commands: ['focus --workspace 2']
    bindings: ['{{ mod }}+{{ focus_workspace_2 }}']
  - commands: ['focus --workspace 3']
    bindings: ['{{ mod }}+{{ focus_workspace_3 }}']
  - commands: ['focus --workspace 4']
    bindings: ['{{ mod }}+{{ focus_workspace_4 }}']
  - commands: ['focus --workspace 5']
    bindings: ['{{ mod }}+{{ focus_workspace_5 }}']
  - commands: ['focus --workspace 6']
    bindings: ['{{ mod }}+{{ focus_workspace_6 }}']
  - commands: ['focus --workspace 7']
    bindings: ['{{ mod }}+{{ focus_workspace_7 }}']
  - commands: ['focus --workspace 8']
    bindings: ['{{ mod }}+{{ focus_workspace_8 }}']
  - commands: ['focus --workspace 9']
    bindings: ['{{ mod }}+{{ focus_workspace_9 }}']
  - commands: ['move-workspace --direction left']
    bindings: ['{{ mod }}+{{ move_left }}']
  - commands: ['move-workspace --direction right']
    bindings: ['{{ mod }}+{{ move_right }}']
  - commands: ['move-workspace --direction up']
    bindings: ['{{ mod }}+{{ move_up }}']
  - commands: ['move-workspace --direction down']
    bindings: ['{{ mod }}+{{ move_down }}']
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['{{ mod }}+{{ move_workspace_1 }}']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['{{ mod }}+{{ move_workspace_2 }}']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['{{ mod }}+{{ move_workspace_3 }}']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['{{ mod }}+{{ move_workspace_4 }}']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['{{ mod }}+{{ move_workspace_5 }}']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['{{ mod }}+{{ move_workspace_6 }}']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['{{ mod }}+{{ move_workspace_7 }}']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['{{ mod }}+{{ move_workspace_8 }}']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['{{ mod }}+{{ move_workspace_9 }}']
