# Keybindings
unbind-key C-b
set -g prefix C-Space
bind-key C-Space send-prefix

bind-key r source-file ~/.config/tmux/tmux.conf \;
bind w command-prompt -p "Enter workspace name" "new-session -d -s '%1' \; switch-client -t '%1'"
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind s display-popup -E -w80% -h80% -b rounded -S fg=#89b4fa "tmux list-sessions -F '#{session_name}' 2>/dev/null | fzf --height=100% --reverse --header='Switch to session:' | xargs -r tmux switch-client -t"

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xsel -ib" \

# Settings
set -gq allow-passthrough on
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g default-shell /bin/zsh
set-option -g status-position top

# Theme
set -g status-style "bg=#181825,fg=#cdd6f4,bold"
set-window-option -g window-status-format "#[fg=#cba6f7,bg=#181825,bold] #(basename #{pane_current_path})"
set-window-option -g window-status-current-format "#[fg=#a6e3a1,bg=#181825,bold] #(basename #{pane_current_path})"
set -g status-left "#[fg=#181825,bold]#{?pane_in_mode,#[bg=#f9e2af] ,#[bg=#89b4fa] } #[bg=#313244]#{?pane_in_mode,#[fg=#f9e2af],#[fg=#89b4fa]} #[bg=#313244]#{?pane_in_mode,#[fg=#f9e2af]#S,#[fg=#89b4fa]#S} #[fg=#313244,bg=#181825] "
set -g status-right "#[bg=#181825,fg=#313244]#[bg=#313244]#{?pane_in_mode,#[fg=#f9e2af] #(basename $SHELL) ,#[fg=#89b4fa] #(basename $SHELL) }#[bg=#313244]#{?pane_in_mode,#[fg=#f9e2af],#[fg=#89b4fa]}#[fg=#181825,bold]#{?pane_in_mode,#[bg=#f9e2af]  ,#[bg=#89b4fa]  }"
set -g pane-border-style fg=#181825
set -g pane-active-border-style fg=#181825

is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?\.?(view|n?vim?x?)(-wrapped)?(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' { if -F '#{pane_at_left}' '' 'select-pane -L' }
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' { if -F '#{pane_at_bottom}' '' 'select-pane -D' }
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' { if -F '#{pane_at_top}' '' 'select-pane -U' }
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' { if -F '#{pane_at_right}' '' 'select-pane -R' }
bind-key -n 'C-n' if-shell "$is_vim" 'send-keys C-n' { if -F '#{window_end_flag}' '' 'select-window -n' }
bind-key -n 'C-p' if-shell "$is_vim" 'send-keys C-p' { if 'test #{window_index} -gt #{base-index}' 'select-window -p' }

bind-key -T copy-mode-vi 'C-h' if -F '#{pane_at_left}' '' 'select-pane -L'
bind-key -T copy-mode-vi 'C-j' if -F '#{pane_at_bottom}' '' 'select-pane -D'
bind-key -T copy-mode-vi 'C-k' if -F '#{pane_at_top}' '' 'select-pane -U'
bind-key -T copy-mode-vi 'C-l' if -F '#{pane_at_right}' '' 'select-pane -R'
bind-key -T copy-mode-vi 'C-n' if -F '#{window_end_flag}' '' 'select-window -n'
bind-key -T copy-mode-vi 'C-p' if 'test #{window_index} -gt #{base-index}' 'select-window -p'

bind -n 'M-h' if-shell "$is_vim" 'send-keys M-h' 'resize-pane -L 1'
bind -n 'M-j' if-shell "$is_vim" 'send-keys M-j' 'resize-pane -D 1'
bind -n 'M-k' if-shell "$is_vim" 'send-keys M-k' 'resize-pane -U 1'
bind -n 'M-l' if-shell "$is_vim" 'send-keys M-l' 'resize-pane -R 1'

bind-key -T copy-mode-vi M-h resize-pane -L 1
bind-key -T copy-mode-vi M-j resize-pane -D 1
bind-key -T copy-mode-vi M-k resize-pane -U 1
bind-key -T copy-mode-vi M-l resize-pane -R 1
