# Keybindings
unbind-key C-b
set -g prefix C-Space
bind-key C-Space send-prefix

bind-key r source-file ~/.config/tmux/tmux.conf \;
bind w command-prompt -p "Enter workspace name" "new-session -d -s '%1' \; switch-client -t '%1'"
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind-key x kill-pane

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xsel -ib" \

# Settings
set -gq allow-passthrough on
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g default-shell /bin/zsh
set-option -g status-position top

set-window-option -g mode-keys vi

# Theme
set -g status-style "bg=#181825,fg=#cdd6f4,bold"
set-window-option -g window-status-format "#[fg=#cba6f7,bg=#181825,bold]  #(basename #{pane_current_path})  "
set-window-option -g window-status-current-format "#[fg=#1e1e2e,bg=#181825]#[fg=#a6e3a1,bg=#1e1e2e,bold] #(basename #{pane_current_path})#{?window_zoomed_flag, ,} #[fg=#1e1e2e,bg=#181825]"
set -g status-left "#[bg=#181825]#[fg=#89b4fa] 󰽙 #S "
set -g status-right "#[bg=#181825] #[fg=#f5c2e7]󰸗 %a, %h %d#[fg=#89b4fa]  %I:%M "
set -g pane-border-style fg=#45475a
set -g pane-active-border-style fg=#45475a
setw -g window-active-style fg=#cdd6f4
setw -g window-style fg=#cdd6f4

# Plugins
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'mrjones2014/smart-splits.nvim'

set -g @sessionx-bind 's'
set -g @sessionx-additional-options "--color pointer:9,spinner:92,marker:46,bg:#1e1e2e,border:#89b4fa"
set -g @sessionx-prompt " "

set -g @smart-splits_no_wrap ''

set -g @smart-splits_move_left_key  'C-h'
set -g @smart-splits_move_down_key  'C-j'
set -g @smart-splits_move_up_key    'C-k'
set -g @smart-splits_move_right_key 'C-l'

set -g @smart-splits_resize_left_key  'M-h'
set -g @smart-splits_resize_down_key  'M-j'
set -g @smart-splits_resize_up_key    'M-k'
set -g @smart-splits_resize_right_key 'M-l'

set -g @smart-splits_resize_step_size '3'

run '~/.tmux/plugins/tpm/tpm'
