[shell.files]
"shell/.bashrc" = "~/.bashrc"

[shell.variables]
shell = "bash"
extras = """
alias cat='batcat'
alias ls='eza'
"""

[terminal]
depends = ["theme"]

[terminal.files]
"terminal/ghostty/config" = "~/.config/ghostty/config"

[tui]
depends = ["theme", "shell"]

[tui.files]
"tui/lazygit/config.yml" = "~/.config/lazygit/config.yml"
"tui/k9s/config.yaml" = "~/.config/k9s/config.yaml"
"tui/k9s/theme.yaml" = "~/.config/k9s/skins/theme.yaml"
"tui/yazi/theme.toml" = "~/.config/yazi/theme.toml"
"tui/tmux/.tmux.conf" = "~/.tmux.conf"

[twm]
depends = ["theme"]

[twm.files]
"twm/linux/i3" = "~/.config/i3"
"twm/linux/polybar" = "~/.config/polybar"
"twm/linux/rofi" = "~/.config/rofi"
