[shell.files]
"shell/.bashrc" = "~/.bashrc"

[shell.variables]
shell = "bash"

[twm]
depends = ["theme"]

[twm.files]
"twm/linux/i3" = "~/.config/i3"
"twm/linux/polybar" = "~/.config/polybar"
"twm/linux/rofi" = "~/.config/rofi"
