[shell.files]
"shell/.zshrc" = "~/.zshrc"

[shell.variables]
shell = "zsh"
extras = """
alias cat='batcat'
alias ls='eza'
"""

[terminal]
depends = ["theme", "shell"]

[terminal.files]
"terminal/wezterm" = "~/.config/wezterm"

[tui]
depends = ["theme", "shell"]

[tui.files]
"tui/lazygit/config.yml" = "~/.config/lazygit/config.yml"
"tui/k9s/config.yaml" = "~/.config/k9s/config.yaml"
"tui/k9s/theme.yaml" = "~/.config/k9s/skins/theme.yaml"
"tui/yazi/theme.toml" = "~/.config/yazi/theme.toml"
"tui/tmux/.tmux.conf" = "~/.tmux.conf"

[twm]
depends = ["theme"]

[twm.files]
"twm/linux/polybar" = "~/.config/polybar"
"twm/linux/rofi" = "~/.config/rofi"
"twm/linux/picom" = "~/.config/picom"
"twm/linux/dunst" = "~/.config/dunst"
"twm/linux/sxhkd" = "~/.config/sxhkd"
"twm/linux/bspwm" = "~/.config/bspwm"
