[linux.variables]
shell_extras = ""

[linux]
depends = ["theme", "twm", "common"]

[linux.files]
"lazygit/config.yml" = "~/.config/lazygit/config.yml"
"k9s/config.yaml" = "~/.config/k9s/config.yaml"
"k9s/theme.yaml" = "~/.config/k9s/skins/theme.yaml"
"yazi/theme.toml" = "~/.config/yazi/theme.toml"
"polybar" = "~/.config/polybar"
"rofi" = "~/.config/rofi"
"picom" = "~/.config/picom"
"dunst" = "~/.config/dunst"
"sxhkd" = "~/.config/sxhkd"
"bspwm" = "~/.config/bspwm"
"scripts/toggle-show-floating.sh" = "~/.local/bin/toggle-show-floating.sh"
"scripts/floating-position.sh" = "~/.local/bin/floating-position.sh"
