[mac.variables]
shell_extras = ""

[mac]
depends = ["theme", "twm", "common"]

[mac.files]
"tui/lazygit/config.yml" = "~/Library/Application Support/lazygit/config.yml"
"tui/k9s/config.yaml" = "~/Library/Application Support/k9s/config.yaml"
"tui/k9s/theme.yaml" = "~/Library/Application Support/k9s/skins/theme.yaml"
"tui/yazi/theme.toml" = "~/.config/yazi/theme.toml"
"twm/mac/aerospace.toml" = "~/.config/aerospace/aerospace.toml"
"twm/mac/skechybar" = "~/.config/sketchybar"
