[shell.files]
"shell/.zshrc" = "~/.zshrc"

[shell.variables]
shell = "zsh"

[tui]
depends = ["theme"]

[tui.files]
"tui/lazygit/config.yml" = "~/Library/Application Support/lazygit/config.yml"
"tui/k9s/config.yaml" = "~/.config/k9s/config.yaml"
"tui/k9s/theme.yaml" = "~/.config/k9s/skins/theme.yaml"
"tui/yazi/theme.toml" = "~/.config/yazi/theme.toml"

[twm.files]
"twm/mac/aerospace.toml" = "~/.config/aerospace/aerospace.toml"
"twm/mac/skechybar" = "~/.config/sketchybar"
