"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](thm_gray)\
$os\
$username\
[](fg:thm_gray bg:thm_black4)\
$directory\
[](fg:thm_black4 bg:thm_green)\
$git_branch\
$git_status\
[](fg:thm_green bg:thm_blue)\
$golang\
$nodejs\
$java\
$python\
[](fg:thm_blue)\
$docker_context\
$conda\
[](fg:thm_gray)\
$line_break$character"""

palette = 'catpuccin_mocha'

[palettes.catpuccin_mocha]
thm_bg="#1e1e2e"
thm_fg="#cdd6f4"
thm_cyan="#89dceb"
thm_black="#181825"
thm_gray="#313244"
thm_magenta="#cba6f7"
thm_pink="#f5c2e7"
thm_red="#f38ba8"
thm_green="#a6e3a1"
thm_yellow="#f9e2af"
thm_blue="#89b4fa"
thm_orange="#fab387"
thm_black4="#4e5166"
[os]
disabled = false
style = "bg:thm_gray fg:thm_green"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Macos = "󰀵"
Linux = "󰌽"

[username]
show_always = true
style_user = "bg:thm_gray fg:thm_green"
style_root = "bg:thm_gray fg:thm_green"
format = '[ $user ]($style)'

[directory]
style = "bg:thm_black4 fg:thm_blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:thm_green fg:thm_gray"
format = '[[ $symbol $branch ](fg:thm_black4 bg:thm_green)]($style)'

[git_status]
style = "bg:thm_green fg:thm_gray"
format = '[[($all_status$ahead_behind )](fg:thm_black4 bg:thm_green)]($style)'

[nodejs]
symbol = ""
style = "bg:thm_blue"
format = '[[ $symbol( $version) ](fg:thm_black4 bg:thm_blue)]($style)'

[golang]
symbol = ""
style = "bg:thm_blue"
format = '[[ $symbol( $version) ](fg:thm_black4 bg:thm_blue)]($style)'

[java]
symbol = " "
style = "bg:thm_blue"
format = '[[ $symbol( $version) ](fg:thm_black4 bg:thm_blue)]($style)'

[python]
symbol = ""
style = "bg:thm_blue"
format = '[[ $symbol( $version) ](fg:thm_black4 bg:thm_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:thm_gray"
format = '[[ $symbol( $context) ](fg:#83a598 bg:thm_gray)]($style)'

[conda]
style = "bg:thm_gray"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:thm_gray)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:thm_green)'
error_symbol = '[](bold fg:thm_red)'
vimcmd_symbol = '[](bold fg:thm_green)'
vimcmd_replace_one_symbol = '[](bold fg:thm_magenta)'
vimcmd_replace_symbol = '[](bold fg:thm_magenta)'
vimcmd_visual_symbol = '[](bold fg:thm_yellow)'
