#!/bin/bash

# Daemons
polybar bar1 &
sleep 1 &
polybar bar2 &
flameshot &
dunst &
nitrogen --restore &
picom --config ~/.config/picom/picom.conf &
sxhkd &
#blueman-applet &

# Monitors

bspc monitor DP-1 -d 1 2 3 4 5

# Configuration

bspc config border_width {{ border_width }}
bspc config window_gap {{ gap }}
bspc config top_padding 22

bspc config split_ratio 0.5
bspc config single_monocle false
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows monocle true
