[helpers]
replace = ".dotter/helpers/replace.rhai"
lower = ".dotter/helpers/lower.rhai"
hextorgba = ".dotter/helpers/hextorgba.rhai"
px = ".dotter/helpers/px.rhai"

[theme.variables]
font = "0xProto Nerd Font Mono"
font_italic = "0xProto"
font_size = "14"
opacity = "1"
inner_gap = "5"
outer_gap = "5"
crust = "#11111b"
mantle = "#181825"
base = "#1e1e2e"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
text = "#cdd6f4"
lavender = "#b4befe"
blue = "#89b4fa"
sapphire = "#74c7ec"
sky = "#89dceb"
teal = "#94e2d5"
green = "#a6e3a1"
yellow = "#f9e2af"
peach = "#fab387"
maroon = "#eba0ac"
red = "#f38ba8"
mauve = "#cba6f7"
pink = "#f5c2e7"
flamingo = "#f2cdcd"
rosewater = "#f5e0dc"
transparent = "#FF00000"

[prompt]
depends = ["theme"]

[prompt.files]
"shell/starship.toml" = "~/.config/starship.toml"

[vscode]
depends = ["theme"]

[vscode.files]
"editor/vscode" = "~/.config/Code/User"

[nvim.files]
"editor/nvim" = "~/.config/nvim"

[wezterm]
depends = ["theme", "shell"]

[wezterm.files]
"wezterm" = "~/.config/wezterm"

[tui]
depends = ["theme"]

[tui.files]
"tui/lazygit/config.yml" = "~/.config/lazygit/config.yml"
"tui/k9s/config.yaml" = "~/.config/k9s/config.yaml"
"tui/k9s/theme.yaml" = "~/.config/k9s/skins/theme.yaml"
"tui/yazi/theme.toml" = "~/.config/yazi/theme.toml"

[twm.variables]
# use i3 syntax (will be translated for others)
mod = "cmd"
terminal = "wezterm"
snipper = "flameshot gui"
restart = "shift+r"
reload = "shift+c"
quit = "shift+q"
exit = "shift+e"
open_terminal = "Enter"
snipping_tool = "shift+s"
application_menu = "space"
toggle_fullscreen = "f"
minimize = "m"
toggle_split = "e"
layout_stacking = "s"
layout_tabbed = "w"
next_workspace = "Tab"
prev_workspace = "shift+Tab"
recent_workspace = "r"
focus_up = "k"
focus_down = "j"
focus_left = "h"
focus_right = "l"
move_up = "shift+k"
move_down = "shift+j"
move_left = "shift+h"
move_right = "shift+l"
focus_workspace_1 = "1"
focus_workspace_2 = "2"
focus_workspace_3 = "3"
focus_workspace_4 = "4"
focus_workspace_5 = "5"
focus_workspace_6 = "6"
focus_workspace_7 = "7"
focus_workspace_8 = "8"
focus_workspace_9 = "9"
move_workspace_1 = "shift+1"
move_workspace_2 = "shift+2"
move_workspace_3 = "shift+3"
move_workspace_4 = "shift+4"
move_workspace_5 = "shift+5"
move_workspace_6 = "shift+6"
move_workspace_7 = "shift+7"
move_workspace_8 = "shift+8"
move_workspace_9 = "shift+9"
increase_height = "o"
decrease_height = "i"
increase_width = "p"
decrease_width = "u"
